### ISSUE TITLE
Does work with hawthorn.

### ISSUE THREAD

**Issue by ross-baker** [dadasoz/edx-bootstrap-theme#11]
I try to install in Hawthorn but I'm getting an error when Assets.

Captured Task Output:
---------------------

---> pavelib.assets.compile_sass
mkdir_p path('/edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/css')
rtlcss /edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/css/bootstrap/lms-main.css /edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/css/bootstrap/lms-main-rtl.css
rtlcss /edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/css/discussion/lms-discussion-bootstrap.css /edx/app/edxapp/edx-platform/themes/edx-bootstrap-theme/lms/static/css/discussion/lms-discussion-bootstrap-rtl.css
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 201, in _run_task
    return do_task()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 198, in do_task
    return func(**kw)
  File "/edx/app/edxapp/edx-platform/pavelib/utils/timer.py", line 39, in timed
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/pavelib/assets.py", line 464, in compile_sass
    timing_info=timing_info
  File "/edx/app/edxapp/edx-platform/pavelib/assets.py", line 548, in _compile_sass
    output_style=output_style,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/sass.py", line 644, in compile
    raise CompileError(v)
CompileError: Error: Incompatible units: 'rem' and 'px'.
        on line 367 of node_modules/bootstrap/scss/_variables.scss
>> $input-height-inner:                    ($font-size-base * $input-btn-line-hei
   -----------------------------------------^

**Comment by jefcolbi** [comment]
Did you resolve this ?

**Comment by publicreading** [comment]
same problem here
