### ISSUE TITLE
CompileError: Error: Incompatible units: 'rem' and 'px'.

### ISSUE THREAD

**Issue by divyanshu9** [dadasoz/edx-bootstrap-theme#12]
---> pavelib.assets.compile_sass
mkdir_p path('/home/ubuntu/edx.custom-theme/themes/custom-theme/lms/static/css')
rtlcss /home/ubuntu/edx.custom-theme/themes/custom-theme/lms/static/css/bootstrap/lms-main.css /home/ubuntu/edx.custom-theme/themes/custom-theme/lms/static/css/bootstrap/lms-main-rtl.css
rtlcss /home/ubuntu/edx.custom-theme/themes/custom-theme/lms/static/css/discussion/lms-discussion-bootstrap.css /home/ubuntu/edx.custom-theme/themes/custom-theme/lms/static/css/discussion/lms-discussion-bootstrap-rtl.css
mkdir_p path('/home/ubuntu/edx.custom-theme/themes/edx-bootstrap-theme-master/lms/static/css')
rtlcss /home/ubuntu/edx.custom-theme/themes/edx-bootstrap-theme-master/lms/static/css/bootstrap/lms-main.css /home/ubuntu/edx.custom-theme/themes/edx-bootstrap-theme-master/lms/static/css/bootstrap/lms-main-rtl.css
rtlcss /home/ubuntu/edx.custom-theme/themes/edx-bootstrap-theme-master/lms/static/css/discussion/lms-discussion-bootstrap.css /home/ubuntu/edx.custom-theme/themes/edx-bootstrap-theme-master/lms/static/css/discussion/lms-discussion-bootstrap-rtl.css
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 201, in _run_task
    return do_task()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 198, in do_task
    return func(**kw)
  File "/edx/app/edxapp/edx-platform/pavelib/utils/timer.py", line 39, in timed
    return wrapped(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/pavelib/assets.py", line 464, in compile_sass
    timing_info=timing_info
  File "/edx/app/edxapp/edx-platform/pavelib/assets.py", line 548, in _compile_sass
    output_style=output_style,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/sass.py", line 644, in compile
    raise CompileError(v)
CompileError: Error: Incompatible units: 'rem' and 'px'.
        on line 367 of node_modules/bootstrap/scss/_variables.scss
>> $input-height-inner:                    ($font-size-base * $input-btn-line-hei
   -----------------------------------------^

**Comment by jonathan-russo** [comment]
I'm also seeing this issue.  Unable to use the theme because it will not build

**Comment by Riadlx** [comment]
It's a great theme but unfortunately incompatible with ironwood release. Hope that @dadasoz could fix it.

**Comment by ratondeau** [comment]
Hi 
I also tried to compile this theme. I am running open edx Koa under Ubuntu 20.5 and getting the same error. What should I do to get this running?
